export const coffees = [
  {
    id: "dsfg",
    brand: "bob's",
    name: "first",
    origin: "Ethiopia",
    description: "a lovely rusty dark roast bitter and chewy in all the right places. Not fruity at all.",
    image: "",
    price: "",
    roast_level: "dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 8,
    nuttyValue: 5,
    sweetValue: 5,
    fruityValue: 0,
    floralValue: 0,
  },
  {
    id: "sadf",
    brand: "Angle coffee",
    name: "wings",
    origin: "Guatamala",
    description: "a high flighing delicious coffee. a real winner. some tones of peach and nutmeg and blackcurrants.",
    image: "",
    price: "",
    roast_level: "medium",
    decaf: false,
    decaf_process: null,
    bitterValue: 3,
    nuttyValue: 5,
    sweetValue: 7,
    fruityValue: 5,
    floralValue: 4,
  },
  {
    id: "cvvvf",
    brand: "Whatsthiscoffee",
    name: "thisisbeans",
    origin: "Guatamala",
    description: "some beautiful beans they are delicious who knows what to do with these tasty beanst roasted to perfection",
    image: "",
    price: "",
    roast_level: "medium",
    decaf: false,
    decaf_process: null,
    bitterValue: 1,
    nuttyValue: 0,
    sweetValue: 0,
    fruityValue: 0,
    floralValue: 0,
  },
  {
    id: "zvcc",
    brand: "Brewsters Beans",
    name: "Bodazzle",
    origin: "Kenya",
    description: "a delightful coffee sourced from Keyna with flavors to scintilate the pallet with floral notes and vanilla sugar.",
    image: null,
    price: "",
    roast_level: "",
    decaf: false,
    decaf_process: null,
    bitterValue: 3,
    nuttyValue: 5,
    sweetValue: 7,
    fruityValue: 5,
    floralValue: 4,
  },
  {
    id: "sfghd",
    brand: "Zing coffee",
    name: "boombastic",
    origin: "Vietnam",
    description: "an oily and medium dark roast blending the bittersweetness of cherries and roasted walnuts.",
    image: null,
    price: "",
    roast_level: "medium-dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 7,
    fruityValue: 6,
    floralValue: 2,
  },
  // Mukilteo coffee Roasters
  {
    id: "000234",
    brand: "Mukilteo",
    name: "Happy Hippie",
    origin: null,
    description: "One of our most popular coffees. This complex blend combines three different varietals and two different roasts to achieve one of our most popular and enduring coffees. The cup is lively and rich, with nutty toffee notes, excellent balance, and vibrant flavor. Far out, man!",
    image: "https://www.mukilteocoffee.com/cdn/shop/files/HH_1024x1024@2x.png?v=1711128757",
    price: "16.00",
    roast_level: "medium",
    decaf: false,
    decaf_process: null,
    bitterValue: 4,
    nuttyValue: 8,
    sweetValue: 5,
    fruityValue: 4,
    floralValue: 3,
  },
  {
    id: "000235",
    brand: "Mukilteo",
    name: "Chetzemoka",
    origin: "",
    description: "A Northwest favorite! Chetzemoka is a blend of Vienna and Italian-roasted coffees that brews up a flavorful and smoky cup with hints of molasses and roasted walnuts. It also makes award-winning espresso!",
    image: "https://www.mukilteocoffee.com/cdn/shop/files/CHETZ_720x.png?v=1711128243",
    price: "16.00",
    roast_level: "medium",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 7,
    fruityValue: 3,
    floralValue: 1,
  },
  {
    id: "000236",
    brand: "Mukilteo",
    name: "Mukilteo",
    origin: "",
    description: "Considered our “Founder's” coffee, this popular blend is wonderful for both espresso and drip-brewed coffee. It is full-bodied and rich without bitterness. The flavor is broad and tangy, with great aromatic dimension. Dry, Well-rounded and not lingering. With hints of dark chocolate and plum.",
    image: "https://www.mukilteocoffee.com/cdn/shop/files/MUK_1024x1024@2x.png?v=1711129076",
    price: "16.00",
    roast_level: "medium",
    decaf: false,
    decaf_process: null,
    bitterValue: 3,
    nuttyValue: 5,
    sweetValue: 7,
    fruityValue: 7,
    floralValue: 2,
  },
  {
    id: "000237",
    brand: "Mukilteo",
    name: "Mukilteo decaf",
    origin: "",
    description: "Earthy tones, smooth and sweet, mild acidity, and creamy texture. This Swiss Water® Process decaf is carefully roasted to bring out rich flavors. You'll find it hard to believe that you're drinking a decaffeinated coffee. Weight: 12 oz.",
    image: "https://www.mukilteocoffee.com/cdn/shop/files/MukDW_1024x1024@2x.png?v=1711129111",
    price: "17.00",
    roast_level: "medium",
    decaf: true,
    decaf_process: "Swiss Water",
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 7,
    fruityValue: 6,
    floralValue: 2,
  },
  {
    id: "000238",
    brand: "Mukilteo",
    name: "French Roast",
    origin: "Guatemala",
    description: "Very dark, with low-acid. The darkest of our roasts, French has a distinctive low acidity, bittersweet pungency, and assertive smoky aroma. Its character is smooth, dark, and tangy, like a fine single-malt Scotch. Delicious with dessert.",
    image: "https://www.mukilteocoffee.com/cdn/shop/files/FRENCH_1024x1024@2x.png?v=1711128383",
    price: "18.00",
    roast_level: "dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 7,
    nuttyValue: 5,
    sweetValue: 7,
    fruityValue: 1,
    floralValue: 1,
  },
  {
    id: "000239",
    brand: "Mukilteo",
    name: "",
    origin: "",
    description: "",
    image: null,
    price: "",
    roast_level: "",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 7,
    fruityValue: 6,
    floralValue: 2,
  },
  {
    id: "00021",
    brand: "Mukilteo",
    name: "",
    origin: "",
    description: "",
    image: null,
    price: "",
    roast_level: "",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 7,
    fruityValue: 6,
    floralValue: 2,
  },
  {
    id: "00023611",
    brand: "Mukilteo",
    name: "",
    origin: "",
    description: "",
    image: "",
    price: "",
    roast_level: "",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 7,
    fruityValue: 6,
    floralValue: 2,
  },
  // Kicking Horse coffee
  {
    id: "000233",
    brand: "Kicking Horse",
    name: "Kick Ass",
    origin: "Indonesia, Central & South America",
    description: "If there’s something worth doing, we think it’s worth doing great. This remarkable blend of beans is the spirit of Kicking Horse® Coffee, and a bold invitation to wake up and kick ass with us. Smoky, sweet vanilla and dark chocolate. Chocolate malt, molasses, licorice and an earthy lingering finish.",
    image: "https://m.media-amazon.com/images/I/31oj637lsFL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "13.99",
    roast_level: "dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 7,
    nuttyValue: 5,
    sweetValue: 7,
    fruityValue: 3,
    floralValue: 4,
  },
  // Brooklyn Lab
  {
    id: "000235",
    brand: "Brooklyn Lab",
    name: "City Roast Sumatra Coffee",
    origin: "Sumatra, Indonesia",
    description: "If there’s something worth doing, we think it’s worth doing great. This remarkable blend of beans is the spirit of Kicking Horse® Coffee, and a bold invitation to wake up and kick ass with us. Smoky, sweet vanilla and dark chocolate. Chocolate malt, molasses, licorice and an earthy lingering finish.",
    image: "https://m.media-amazon.com/images/I/31oj637lsFL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "13.99",
    roast_level: "dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 6,
    sweetValue: 4,
    fruityValue: 6,
    floralValue: 1,
  },
  {
    id: "0002233",
    brand: "Colombia",
    name: "Whole Bean Coffee Medium Roast",
    origin: "Colombia",
    description: "Balanced, full-bodied medium roast with a smooth finish",
    image: "https://m.media-amazon.com/images/I/31oj637lsFL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "11.51",
    roast_level: "medium",
    decaf: false,
    decaf_process: null,
    bitterValue: 3,
    nuttyValue: 3,
    sweetValue: 4,
    fruityValue: 4,
    floralValue: 2,
  },
  {
    id: "00023525",
    brand: "Death Wish Coffee Co.",
    name: "Dark Roast",
    origin: "Colombia",
    description: "Immerse yourself in a smooth, subtle cherry and chocolate flavor profile that is never bitter. We've thoughtfully and carefully selected premium Arabica and Robusta whole coffee beans from around the world to deliver you a coffee beans dark roast beverage with a bold taste you’ll find irresistible and instantly fall in love with.",
    image: "https://m.media-amazon.com/images/I/61nsKameQEL._SX679_.jpg",
    price: "14.09",
    roast_level: "dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 5,
    nuttyValue: 7,
    sweetValue: 2,
    fruityValue: 6,
    floralValue: 1,
  },
  // Blue Bottle
  {
    id: "00012222",
    brand: "Blue Bottle",
    name: "Playlist",
    origin: "Colombia",
    description: "This blend is like the pair of adult siblings who, after years of talking over one another at the dinner table, finally get along. Two distinct washed coffees become mild and sweet, with flickers of brightness and whispers of fruit. How nice to know that this coffee blend, like family, finds balance when mixed in the right proportions.",
    image: "https://res.cloudinary.com/hbhhv9rz9/image/upload/f_auto,c_limit,w_2048,q_auto/2024/2024%20Updated%20Packaging/Playlist%20Blend/M1_Playlist_Hero.png",
    price: "13.00",
    roast_level: "light",
    decaf: false,
    decaf_process: null,
    bitterValue: 1,
    nuttyValue: 3,
    sweetValue: 6,
    fruityValue: 6,
    floralValue: 1,
  },
  {
    id: "0002353335",
    brand: "Blue Bottle",
    name: "Hayes Valley Espresso",
    origin: "Colombia",
    description: "Hayes Valley is a consistent guest favorite: the foundation of our cafe espresso drinks and a best seller for whole bean coffee. It’s also our darkest espresso on the menu and completely organic — what’s not to love? Sip it straight to appreciate the voluptuous tawny crema and impressive viscosity. Or add milk to soften its brooding aspects for a sweeter yet assertive drink.",
    image: "https://res.cloudinary.com/hbhhv9rz9/image/upload/f_auto,c_limit,w_2048,q_auto/2024/2024%20Updated%20Packaging/Hayes%20Valley%20Espresso/M1_HayesValleyEspresso_Hero.png",
    price: "13.00",
    roast_level: "dark",
    decaf: false,
    decaf_process: null,
    bitterValue: 6,
    nuttyValue: 7,
    sweetValue: 5,
    fruityValue: 5,
    floralValue: 1,
  },

]


// using the coffee taster's flavor wheel
// export const coffees = [
//   {
//     coffee_id: "saaffddf",
//     brand: "",
//     name: "",
//     image: "",
//     price: "15.99",
//     origin: "Brazil",
//     roast_level: "dark",
//     description: "very dark and oily and nice",
//     harvest_date: "2022-12-06",
//     reviews: {
//       rating: "",
//       review: "very nice yah"
//     },
//     process_method: null,
//     cultivar: null,
//     farm_gate: true,
//     inner: {
//       roasted: 1,
//       spices: 2,
//       nutty_cocoa: 1,
//       sweet: 2,
//       floral: 3,
//       fruity: 3,
//       sour_fermented: 2,
//       green_vegetative: 1,
//       other: 1
//     },
//     middle: {
//       berry: 6,
//       dried_fruit: 8,
//       other_fruit: 3,
//       citrus_fruit: 2,
//       sour: 1,
//       alcohol_fermented: 1,
//       olive_oil: 7,
//       raw: 7,
//       green_vegitative: 4,
//       beany: 9,
//       papery_musty: 2,
//       chemical: 4,
//       pipe_tobacco: 3,
//       tobacco: 4,
//       burnt: 5,
//       cereal: 6,
//       pungent: 8,
//       pepper: 3,
//       nutty: 3,
//       cocoa: 8,
//       brown_sugar: 7,
//       vanilla: 1,
//       vanillin: 0,
//       overall_sweet: 4,
//       sweet_aromatics: 6,
//       black_tea: 4,
//       floral: 2
//     },
//     outer: {
//       // Roasted
//       tobacco: 0,
//       pipe_tobacco: 0,
//       burnt: 0,
//       cereal: 0,
//       malt: 0,
//       grain: 0,
      
//       // Spices
//       pepper: 0,
//       pungent: 0,
//       nutmeg: 0,
//       cinnamon: 0,
//       clove: 0,
//       anise: 0,

//       // Nutty/Cocoa
//       cocoa: 0,
//       dark_chocolate: 0,
//       milk_chocolate: 0,
//       almond: 0,
//       hazelnut: 0,
//       peanut: 0,

//       // Sweet
//       brown_sugar: 0,
//       caramelized: 0,
//       honey: 0,
//       maple_syrup: 0,
//       molasses: 0,

//       // Floral
//       jasmine: 0,
//       chamomile: 0,
//       rose: 0,
//       black_tea: 0,

//       // Fruity
//       blackberry: 0,
//       raspberry: 0,
//       blueberry: 0,
//       strawberry: 0,
//       raisin: 0,
//       prune: 0,
//       coconut: 0,
//       cherry: 0,
//       pomegranate: 0,
//       pineapple: 0,
//       grape: 0,
//       apple: 0,
//       pear: 0,
//       grapefruit: 0,
//       orange: 0,
//       lemon: 0,
//       lime: 0,

//       // Sour/Fermented
//       sour_aromatics: 0,
//       acetic_acid: 0,
//       butyric_acid: 0,
//       isovaleric_acid: 0,
//       citric_acid: 0,
//       malic_acid: 0,

//       // Green/Vegetative
//       under_ripe: 0,
//       peapod: 0,
//       fresh: 0,
//       dark_green: 0,
//       vegetative: 0,
//       hay_like: 0,
//       herby: 0,

//       // Other
//       papery: 0,
//       musty: 0,
//       dusty: 0,
//       moldy_damp: 0,
//       woody: 0,
//       cardboard: 0,
//       rubber: 0,
//       skunky: 0,
//       petroleum: 0
//     }
//   },
//   {
//     coffee_id: "brazil-dark-001",
//     brand: "Coffee Roasters Inc.",
//     name: "Brazilian Midnight Roast",
//     price: "15.99",
//     origin: "Brazil",
//     roast_level: "dark",
//     description: "A bold, full-bodied coffee with rich cocoa and nutty undertones.",
//     harvest_date: "2022-12-06",
//     reviews: {
//       rating: "4.5",
//       review: "Rich and smooth, perfect for dark roast lovers."
//     },
//     process_method: "Natural",
//     cultivar: "Bourbon",
//     farm_gate: true,
//     inner: {
//       roasted: 8,
//       spices: 6,
//       nutty_cocoa: 9,
//       sweet: 5,
//       floral: 2,
//       fruity: 3,
//       sour_fermented: 1,
//       green_vegetative: 2,
//       other: 1
//     },
//     middle: {
//       berry: 4,
//       dried_fruit: 7,
//       other_fruit: 3,
//       citrus_fruit: 2,
//       sour: 1,
//       alcohol_fermented: 1,
//       olive_oil: 3,
//       raw: 2,
//       green_vegitative: 3,
//       beany: 6,
//       papery_musty: 1,
//       chemical: 1,
//       pipe_tobacco: 5,
//       tobacco: 6,
//       burnt: 8,
//       cereal: 6,
//       pungent: 7,
//       pepper: 4,
//       nutty: 8,
//       cocoa: 9,
//       brown_sugar: 7,
//       vanilla: 3,
//       vanillin: 2,
//       overall_sweet: 6,
//       sweet_aromatics: 7,
//       black_tea: 2,
//       floral: 3
//     },
//     outer: {
//       // Roasted
//       tobacco: 6,
//       pipe_tobacco: 5,
//       burnt: 8,
//       cereal: 6,
//       malt: 7,
//       grain: 6,
      
//       // Spices
//       pepper: 4,
//       pungent: 7,
//       nutmeg: 5,
//       cinnamon: 3,
//       clove: 3,
//       anise: 2,

//       // Nutty/Cocoa
//       cocoa: 9,
//       dark_chocolate: 8,
//       milk_chocolate: 5,
//       almond: 7,
//       hazelnut: 8,
//       peanut: 6,

//       // Sweet
//       brown_sugar: 7,
//       caramelized: 8,
//       honey: 4,
//       maple_syrup: 6,
//       molasses: 5,

//       // Floral
//       jasmine: 2,
//       chamomile: 1,
//       rose: 1,
//       black_tea: 2,

//       // Fruity
//       blackberry: 2,
//       raspberry: 3,
//       blueberry: 3,
//       strawberry: 2,
//       raisin: 7,
//       prune: 6,
//       coconut: 2,
//       cherry: 3,
//       pomegranate: 3,
//       pineapple: 2,
//       grape: 2,
//       apple: 2,
//       pear: 2,
//       grapefruit: 1,
//       orange: 2,
//       lemon: 1,
//       lime: 1,

//       // Sour/Fermented
//       sour_aromatics: 1,
//       acetic_acid: 1,
//       butyric_acid: 0,
//       isovaleric_acid: 0,
//       citric_acid: 1,
//       malic_acid: 1,

//       // Green/Vegetative
//       under_ripe: 2,
//       peapod: 1,
//       fresh: 2,
//       dark_green: 1,
//       vegetative: 1,
//       hay_like: 1,
//       herby: 2,

//       // Other
//       papery: 1,
//       musty: 0,
//       dusty: 1,
//       moldy_damp: 0,
//       woody: 2,
//       cardboard: 1,
//       rubber: 0,
//       skunky: 0,
//       petroleum: 0
//     }
//   },
//   // Third coffee entry
//   {
//     coffee_id: "ethiopia-washed-003",
//     brand: "Ethiopian Coffee Co.",
//     name: "Ethiopian Sunrise",
//     price: "18.99",
//     origin: "Ethiopia",
//     roast_level: "medium",
//     description: "A bright, floral coffee with notes of citrus and jasmine, perfect for a refreshing start to the day.",
//     harvest_date: "2023-10-15",
//     reviews: {
//       rating: "4.8",
//       review: "Delicate and vibrant, one of the best Ethiopian coffees I've tasted!"
//     },
//     process_method: "Washed",
//     cultivar: "Heirloom",
//     farm_gate: true,
//     inner: {
//       roasted: 3,
//       spices: 2,
//       nutty_cocoa: 2,
//       sweet: 7,
//       floral: 9,
//       fruity: 8,
//       sour_fermented: 1,
//       green_vegetative: 2,
//       other: 1
//     },
//     middle: {
//       berry: 7,
//       dried_fruit: 4,
//       other_fruit: 9,
//       citrus_fruit: 10,
//       sour: 3,
//       alcohol_fermented: 1,
//       olive_oil: 2,
//       raw: 2,
//       green_vegitative: 2,
//       beany: 3,
//       papery_musty: 1,
//       chemical: 0,
//       pipe_tobacco: 1,
//       tobacco: 1,
//       burnt: 1,
//       cereal: 2,
//       pungent: 1,
//       pepper: 1,
//       nutty: 2,
//       cocoa: 3,
//       brown_sugar: 5,
//       vanilla: 4,
//       vanillin: 2,
//       overall_sweet: 8,
//       sweet_aromatics: 9,
//       black_tea: 8,
//       floral: 10
//     },
//     outer: {
//       // Roasted
//       tobacco: 0,
//       pipe_tobacco: 0,
//       burnt: 0,
//       cereal: 1,
//       malt: 1,
//       grain: 1,

//       // Spices
//       pepper: 0,
//       pungent: 0,
//       nutmeg: 0,
//       cinnamon: 0,
//       clove: 0,
//       anise: 0,

//       // Nutty/Cocoa
//       cocoa: 2,
//       dark_chocolate: 1,
//       milk_chocolate: 1,
//       almond: 1,
//       hazelnut: 1,
//       peanut: 1,

//       // Sweet
//       brown_sugar: 3,
//       caramelized: 2,
//       honey: 6,
//       maple_syrup: 4,
//       molasses: 2,

//       // Floral
//       jasmine: 10,
//       chamomile: 8,
//       rose: 7,
//       black_tea: 8,

//       // Fruity
//       blackberry: 4,
//       raspberry: 5,
//       blueberry: 4,
//       strawberry: 3,
//       raisin: 2,
//       prune: 1,
//       coconut: 1,
//       cherry: 6,
//       pomegranate: 4,
//       pineapple: 5,
//       grape: 7,
//       apple: 6,
//       pear: 5,
//       grapefruit: 8,
//       orange: 7,
//       lemon: 9,
//       lime: 8,

//       // Sour/Fermented
//       sour_aromatics: 2,
//       acetic_acid: 1,
//       butyric_acid: 0,
//       isovaleric_acid: 0,
//       citric_acid: 10,
//       malic_acid: 8,

//       // Green/Vegetative
//       under_ripe: 2,
//       peapod: 1,
//       fresh: 3,
//       dark_green: 2,
//       vegetative: 1,
//       hay_like: 1,
//       herby: 1,

//       // Other
//       papery: 0,
//       musty: 0,
//       dusty: 0,
//       moldy_damp: 0,
//       woody: 1,
//       cardboard: 0,
//       rubber: 0,
//       skunky: 0,
//       petroleum: 0
//     }
//   }
// ];


// Or using sweet maria's guide

// const coffees = [
//   {
//     coffee_id: "saaffddf",
//     brand: "",
//     name: "",
//     price: "15.99",
//     origin: 'brazil',
//     date: '2022-12-06',
//     reviews: 4,
//     process_method: null,
//     cultivar: null,
//     farm_gate: true,
//     cup_flavors: {
//       fragrance: "d",
//       wet_aroma: "d",
//       brightness: "",
//       flavor: "",
//       body: "",
//       finish: "",
//       sweetness: "",
//       clean_cup: "",
//       complexity: "",
//       uniformity: "",
//     },
//     flavors: {
//       floral: "",
//       honey: "",
//       sugars: "",
//       caramel: "",
//       fruits: "",
//       citrus: "",
//       berry: "",
//       cocoa: "",
//       nuts: "",
//       rustic: "",
//       spice: "",
//       body: "",
//     }
//   }
// ]